### ISSUE TITLE
Use of async is deprecated

### ISSUE THREAD

**Issue by ForrestCKoch** [vlukiyanov/pt-sdae#1]
Hi,

I've just been trying out your code in Python 3.7 (to be fair you only mention support for 3.6), and I experience a crash when trying to import ptsdae.model:
```
>>> import ptsdae.model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked                                                          
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec                                                              
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec                                                              
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec                                                       
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader                                                                 
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location                                                 
  File "/usr/lib/python3.7/site-packages/ptsdae-1.0-py3.7.egg/ptsdae/model.py", line 87                                               
    batch = batch.cuda(async=True)
                           ^
SyntaxError: invalid syntax
```

It seems this is because async is now a reserved word as of 3.7. 
See also: https://github.com/pytorch/pytorch/blob/4d28b65fb8978f1c34765d56f18c07042e70a43a/torch/_utils.py#L20-L21
https://github.com/facebookresearch/adversarial_image_defenses/issues/14 

As a side note may I just mention that your code is very well written!  I really appreciate your coding style (and use of comments in particular).

**Comment by vlukiyanov** [comment]
Should be fixed now. I've tested with CUDA too, using `python mnist.py --cuda=True --pretrain-epochs=1 --finetune-epochs=1`.
